### ISSUE TITLE
Warning: DOMDocument::loadHTML():

### ISSUE THREAD

**Issue by AzioArv** [kadekjayak/bca-parser#1]
Warning: DOMDocument::loadHTML(): Opening and ending tag mismatch: td and font in Entity, line: 49 in BCAParser.php on line 204

Warning: DOMDocument::loadHTML(): Opening and ending tag mismatch: td and b in Entity, line: 74 in BCAParser.php on line 204

Warning: DOMDocument::loadHTML(): Opening and ending tag mismatch: td and b in Entity, line: 75 in BCAParser.php on line 204

**Comment by kadekjayak** [comment]
biasanya karena salah password, atau kena limit login...
coba nanti saya cek...

**Comment by kadekjayak** [comment]
#c257698  will hide the message
