### ISSUE TITLE
Get saldo error 302

### ISSUE THREAD

**Issue by wawanrandianto1** [kadekjayak/bca-parser#10]
"""
<html><head><title>302 Moved Temporarily</title></head>
<body bgcolor="#FFFFFF">
<p>This document you requested has moved 
temporarily.</p>
<p>It's now at <a href="https://m.klikbca.com/authentication.do?value&#40;actions&#41;=logout">https://m.klikbca.com/authentication.do?value&#40;actions&#41;=lo[ ▶]()
</body></html>
"""

**Comment by tarikhagustia** [comment]
same here

**Comment by kadekjayak** [comment]
#11 Thank you @tarikhagustia

**Comment by ace3** [comment]
tried using it to get mutasi, still have 302 redirects.
