### ISSUE TITLE
Attempt to read property "nodeValue" on null

### ISSUE THREAD

**Issue by luqmansolihin** [kadekjayak/bca-parser#14]
`
            {
                "class": "ErrorException",
                "message": "Attempt to read property \"nodeValue\" on null",
                "code": 0,
                "file": "/var/www/api_app/vendor/kadekjayak/bca-parser/src/BCAParser.php:332",
                "trace": [
                    "/var/www/api_app/vendor/kadekjayak/bca-parser/src/BCAParser.php:332",
                    "/var/www/api_app/vendor/kadekjayak/bca-parser/src/BCAParser.php:363",
                    "/var/www/api_app/vendor/kadekjayak/bca-parser/src/BCAParser.php:378",
                    "/var/www/api_app/app/Services/BankMutationService.php:16",
                    "/var/www/api_app/app/Services/BankMutationService.php:25",
                    "/var/www/api_app/app/Console/Commands/BankMutationCron.php:46",
                    "/var/www/api_app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:36",
                    "/var/www/api_app/vendor/laravel/framework/src/Illuminate/Container/Util.php:40",
                    "/var/www/api_app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:93",
                    "/var/www/api_app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:37",
                    "/var/www/api_app/vendor/laravel/framework/src/Illuminate/Container/Container.php:653",
                    "/var/www/api_app/vendor/laravel/framework/src/Illuminate/Console/Command.php:136",
                    "/var/www/api_app/vendor/symfony/console/Command/Command.php:298",
                    "/var/www/api_app/vendor/laravel/framework/src/Illuminate/Console/Command.php:121",
                    "/var/www/api_app/vendor/symfony/console/Application.php:1024",
                    "/var/www/api_app/vendor/symfony/console/Application.php:299",
                    "/var/www/api_app/vendor/symfony/console/Application.php:171",
                    "/var/www/api_app/vendor/laravel/framework/src/Illuminate/Console/Application.php:94",
                    "/var/www/api_app/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php:129",
                    "/var/www/api_app/artisan:37"
                ]
            }
`

error seperti ini muncul karena apa ya?

**Comment by fedry** [comment]
sepertinya karena mobile klikbca sekarang uda mesti enable javascript.. saya coba debug function login() juga uda gagal. T_T

**Comment by kadekjayak** [comment]
@fedry wah kalau begitu metode scraping ini kemungkinan tidak bisa digunakan lagi...

**Comment by ace3** [comment]
ini saya kebetulan menggunakan script single php file, modif sendiri, dengan ngambil inspirasi dari sini, dan masi jalan.

**Comment by fedry** [comment]
> ini saya kebetulan menggunakan script single php file, modif sendiri, dengan ngambil inspirasi dari sini, dan masi jalan.

kalau masih jalan, bole di-share script utk bagian loginnya? :)

**Comment by ace3** [comment]
```php

$this->conf['ip'] = 'x.x.x.x';
date_default_timezone_set('Asia/Jakarta');
$this->conf['time'] = time();
$this->conf['path'] = dirname(__FILE__);

function login($username, $password)
    {
        $this->ch = curl_init();
        
        curl_setopt($this->ch, CURLOPT_USERAGENT, 'Mozilla/5.0 (Linux; U; Android 2.3.7; en-us; Nexus One Build/GRK39F) AppleWebKit/533.1 (KHTML, like Gecko) Version/4.0 Mobile Safari/533.1');
        curl_setopt($this->ch, CURLOPT_URL, 'https://m.klikbca.com/login.jsp');
        curl_setopt($this->ch, CURLOPT_COOKIEFILE, $this->conf['path'] . '/cookie');
        curl_setopt($this->ch, CURLOPT_COOKIEJAR, $this->conf['path'] . '/cookiejar');
        
        $this->curlexec();
        
        $params = implode('&', array('value(user_id)=' . $username, 'value(pswd)=' . $password, 'value(Submit)=LOGIN', 'value(actions)=login', 'value(user_ip)=' . $this->conf['ip'], 'user_ip=' . $this->conf['ip'], 'value(mobile)=true', 'mobile=true'));
        
        curl_setopt($this->ch, CURLOPT_URL, 'https://m.klikbca.com/authentication.do');
        curl_setopt($this->ch, CURLOPT_REFERER, 'https://m.klikbca.com/login.jsp');
        curl_setopt($this->ch, CURLOPT_POSTFIELDS, $params);
        curl_setopt($this->ch, CURLOPT_POST, 1);
        
        $this->curlexec();
    }
```

**Comment by kadekjayak** [comment]
hmm, spertinya terkait masalah saat resolve ip address

**Comment by fedry** [comment]
> hmm, spertinya terkait masalah saat resolve ip address

iya.. ini masalah jg.
tapi saya hardcode ip addressnya, tetep gak bisa jalan jg...

ada yg berhasil setelah di hardcode ip addressnya?

**Comment by ace3** [comment]
di library nya ada menggunakan 3rd party untuk mendapatkan ip , mungkin bisa di ganti dengan 
```php
$ip_address = getHostByName(getHostName());
```

**Comment by kadekjayak** [comment]
@fedry hari ini saya test dengan IP manual masih bisa mas ambil transaksi...

**Comment by kadekjayak** [comment]
@luqmansolihin barusan saya update ip resolver nya dan masih berfungsi dengan baik.

ef86bfebad511e577550b9dc069d7e96d2c0e18d

**Comment by luqmansolihin** [comment]
@kadekjayak terimakasih, sudah solve sekarang.

**Comment by fedry** [comment]
yes.. ini uda sembuh... :)
