### ISSUE TITLE
file_get_contents([https://api.ipify.org?format=json](https://api.ipify.org/?format=json)): Failed to open stream: HTTP request failed! HTTP/1.1 503 Service Unavailable\r\n

### ISSUE THREAD

**Issue by luqmansolihin** [kadekjayak/bca-parser#15]
{
    "class": "ErrorException",
    "message": "file_get_contents(https://api.ipify.org?format=json): Failed to open stream: HTTP request failed! HTTP/1.1 503 Service Unavailable\r\n",
    "code": 0,
    "file": "/var/www/api_project/vendor/kadekjayak/bca-parser/src/BCAParser.php:80",
    "trace": [
        "/var/www/api_project/vendor/kadekjayak/bca-parser/src/BCAParser.php:80",
        "/var/www/api_project/vendor/kadekjayak/bca-parser/src/BCAParser.php:164",
        "/var/www/api_project/vendor/kadekjayak/bca-parser/src/BCAParser.php:268",
        "/var/www/api_project/vendor/kadekjayak/bca-parser/src/BCAParser.php:381",
        "/var/www/api_project/vendor/kadekjayak/bca-parser/src/BCAParser.php:397",
        "/var/www/api_project/app/Services/BankMutationService.php:16",
        "/var/www/api_project/app/Services/BankMutationService.php:25",
        "/var/www/api_project/app/Console/Commands/BankMutationCron.php:46",
        "/var/www/api_project/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:36",
        "/var/www/api_project/vendor/laravel/framework/src/Illuminate/Container/Util.php:40",
        "/var/www/api_project/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:93",
        "/var/www/api_project/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:37",
        "/var/www/api_project/vendor/laravel/framework/src/Illuminate/Container/Container.php:653",
        "/var/www/api_project/vendor/laravel/framework/src/Illuminate/Console/Command.php:136",
        "/var/www/api_project/vendor/symfony/console/Command/Command.php:298",
        "/var/www/api_project/vendor/laravel/framework/src/Illuminate/Console/Command.php:121",
        "/var/www/api_project/vendor/symfony/console/Application.php:1040",
        "/var/www/api_project/vendor/symfony/console/Application.php:301",
        "/var/www/api_project/vendor/symfony/console/Application.php:171"
    ]
}

**Comment by ace3** [comment]
ini kebetulan service buat dapetin IP address nya down saja.
silahkan dicoba lagi skrg, dan klo ga bisa, apakah url https://api.ipify.org/?format=json bisa di akses ?

**Comment by kadekjayak** [comment]
Hi Gaes, 

bagi yang servernya pakai `IP Public static`, bisa kasi parameter ip tersebut ke class ketika initialization agar tidak bergantung ke 3rd party services.

contohnya:
```
$Parser = new BCAParser('username', 'password', "192.168.1.1");
```

Thanks :)
