### ISSUE TITLE
Undefined offset: 1

### ISSUE THREAD

**Issue by Qiun2** [kadekjayak/bca-parser#6]
Apakah ini bisa digunakan untuk KlikBCA bisnis? Karena waktu dicoba keluar error..
Trims

**Comment by Qiun2** [comment]
Error sudah bisa diselesaikan.. tq

**Comment by kadekjayak** [comment]
@Qiun2 Error nya apa ya kalo boleh tau?

karena saya tidak punya BCA bisnis jadi tidak bisa coba, kalo elemen html klik bca nya sama seharusnya tidak ada masalah...

**Comment by Qiun2** [comment]
Sepertinya elemen html nya sama. Sy cek errornya keluar kl ada transaksi yg tulisannya PEND (Pending)

**Comment by kadekjayak** [comment]
kemungkinan parsing date nya, akan saya cek..
